services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: back
    env_file:
      - ./back/.env
    ports:
      - 8080:8080
    volumes:
      - ./back:/usr/src/app
    tty: true

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: front
    env_file:
      - ./front/.env
    ports:
      - 3000:3000
    volumes:
      - ./front:/usr/src/app

      - front_node_modules:/usr/src/app/node_modules
    tty: true

volumes:
  front_node_modules:
